// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56DjIbbwsGFcbf8el9w-j4tcCu2oivj4',
    appId: '1:83390199673:web:b4a8d92082a2de0506e1a8',
    messagingSenderId: '83390199673',
    projectId: 'crud-9a54e',
    authDomain: 'crud-9a54e.firebaseapp.com',
    storageBucket: 'crud-9a54e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFiyFuB5R1Akb63OBIZeJir11BBKXQu0',
    appId: '1:83390199673:android:08763d76af4f921106e1a8',
    messagingSenderId: '83390199673',
    projectId: 'crud-9a54e',
    storageBucket: 'crud-9a54e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMFyUnEvDUIa41NV8zP01ZyUep1qAhKA',
    appId: '1:83390199673:ios:6a1ddc832d8caf9306e1a8',
    messagingSenderId: '83390199673',
    projectId: 'crud-9a54e',
    storageBucket: 'crud-9a54e.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNMFyUnEvDUIa41NV8zP01ZyUep1qAhKA',
    appId: '1:83390199673:ios:bf58db8add1ffc9a06e1a8',
    messagingSenderId: '83390199673',
    projectId: 'crud-9a54e',
    storageBucket: 'crud-9a54e.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
